name: Check for duplicate opcodes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.5
    - name: Install dependencies
      run: nuget restore
    - name: Build DotNet4
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\..\MachinaWrapperJSON.sln /t:Build /p:Configuration=Release
    - name: Check for duplicate opcodes
      run: ./MachinaWrapper/bin/Release/MachinaWrapper.exe --Test
